language: java
jdk:
  - openjdk11

# Встановлення залежностей
install: true

# Запуск тестів
script:
  - mvn clean test

# Створення та публікація Docker-образу після успішних тестів
after_success:
  - docker build -t gcr.io/my-project-436711/carshop .
  - echo "$GCLOUD_SERVICE_KEY" | docker login -u _json_key --password-stdin https://gcr.io
  - docker push gcr.io/my-project-436711/carshop
